### ISSUE TITLE
Peakhood cannot open .2bit file

### ISSUE THREAD

**Issue by Braulium** [BackofenLab/Peakhood#6]
Dear Peakhood team,

I tryed to use peakhood on eCLIP data on a cytoplasmid RBP, but it crashes at the first step, it seems it is not able to open the .2bit file:
`Traceback (most recent call last):
  File "/scicore/home/scheiffe/ortiz0000/anaconda3/envs/peakhood/bin/peakhood", line 5770, in <module>
    main_extract(args)
  File "/scicore/home/scheiffe/ortiz0000/anaconda3/envs/peakhood/bin/peakhood", line 886, in main_extract
    chr_len_dic = hoodlib.get_chromosome_lengths_from_2bit(args.in_2bit, chr_lengths_file)
  File "/scicore/home/scheiffe/ortiz0000/anaconda3/envs/peakhood/lib/python3.8/site-packages/peakhood/hoodlib.py", line 278, in get_chromosome_lengths_from_2bit
    assert error == False, "twoBitInfo is complaining:\n%s\n%s" %(check_cmd, output)
AssertionError: twoBitInfo is complaining:
twoBitInfo mm10.2bit EIF3G_eCLIP_IDR_extract_out/reference_lengths.out
twoBitInfo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
`

When I try to get information about the mm10.2bit using twoBitInfo, the same error arises:
`(peakhood) twoBitInfo mm10.2bit`
`twoBitInfo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
`

Do you have any idea of what am I doing wrong?

Thanks a lot.

Best regards,
Raul

**Comment by michauhl** [comment]
Hi Raul, thanks for your interest! I'm a bit busy this week, will have a look at it on Friday and reply. Best, Michael

**Comment by michauhl** [comment]
Did you install it via conda?  (conda install -c bioconda peakhood) Looks vaguely familiar the error yes ...

**Comment by Braulium** [comment]
Hi Michael, thanks for your fast reply!

Yes, I installed it through Conda, exactly as it is indicated in the README:

conda create -n peakhood python=3.8 -c conda-forge -c bioconda

conda activate peakhood

conda install -c bioconda peakhood

**Comment by michauhl** [comment]
Okay, I tried the installation on two computers (Ubuntu 20 + 22), conda version is 22.9.0, Python versions tested both 3.8 and 3.11. Everything works, but yes I remember this error from some time ago. It is also reported on forums for different tools (e.g. https://github.com/merenlab/anvio/issues/1479). Have you tried this suggestion from the Peakhood installation instructions?
conda config --add channels bioconda
conda config --add channels conda-forge

**Comment by Braulium** [comment]
Hi Michael,

Yes, I installed Peakhood following the instructions from Github, and I used:
conda config --add channels bioconda
conda config --add channels conda-forge

The installation seemed to work fine, the problem arises when trying to execute it with peakhood extract.
Thanks again.

Best regards,
Raul

**Comment by michauhl** [comment]
I see, did you also retry to create the environment and install after the commands? There are a number of solutions proposed for this online (maybe "conda update conda" also helps). Or maybe the dataset is part of the supplement already? (https://zenodo.org/record/5557101)

**Comment by michauhl** [comment]
Here are my environment dependencies:

```
$ conda list
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bedtools                  2.30.0               h468198e_3    bioconda
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
contourpy                 1.0.6            py38h43d8883_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
fonttools                 4.38.0           py38h0a891b7_1    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
importlib-metadata        5.1.0              pyha770c72_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
kiwisolver                1.4.4            py38h43d8883_1    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.2.0                hf544144_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
matplotlib-base           3.6.2            py38hb021067_0    conda-forge
munkres                   1.0.7                      py_1    bioconda
mysql-connector-c         6.1.6                         2    bioconda
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.23.5           py38h7042d01_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   3.0.7                h0b41bf4_1    conda-forge
packaging                 22.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.2            py38h8f669ce_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
peakhood                  0.3                pyhdfd78af_0    bioconda
pillow                    8.2.0            py38ha0e1e83_1    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
python                    3.8.15          h4a9ceb5_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
samtools                  1.3.1                         0    bioconda
scipy                     1.9.3            py38h8ce737c_2    conda-forge
seaborn                   0.12.1               hd8ed1ab_0    conda-forge
seaborn-base              0.12.1             pyhd8ed1ab_0    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
statsmodels               0.13.5           py38h26c90d9_2    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
ucsc-twobitinfo           357                           0    bioconda
ucsc-twobittofa           357                           0    bioconda
unicodedata2              15.0.0           py38h0a891b7_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.11.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge


```
